### ISSUE TITLE
Issue in whitelist match for bd-rhapsody

### ISSUE THREAD

**Issue by LorenzoLF** [minoda-lab/universc#15] opened 2023-05-06 16:08 UTC
Dear UniverSC developers and community,

I am running UniverSC for bd-rhapsody fastqs (cellranger 3.0.2. installed) and the run goes smoothly but there seems to be no barcode match:

**whitelist setup begin
updating barcodes in cellranger-3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes for Cell Ranger version 3.0.2 installed in rhapsody/cellranger-3.0.2/cellranger ...
 restoring Cell Ranger
sed: can't read rhapsody/cellranger-3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/check.py: No such file or directory
 rhapsody/cellranger-3.0.2/cellranger set for bd-rhapsody
 converting whitelist
barcode adjust: 0
 whitelist converted**

As a result, cellranger fails to recognize the barcodes:

**[error] You selected chemistry 'SC3Pv2', which expects the cell barcode sequence in read R1.
In input data, an extremely low rate of correct barcodes was observed for this chemistry (0.00 %).
Please check your input data and chemistry selection. Note: manual chemistry detection is not required in most cases.**

Any help would be highly appreciated. Thank you very much.

**Comment by TomKellyGenetics** [comment] 2023-05-13 14:17
Thanks for reporting this issue, we are already aware of problems with this technology configuration, as reported by @Davidwei7 (#13) @paramitadutta14 (#14) and are investigating the root cause.

I’m responsible for this part of the code base and have been on holiday or busy with other projects. I initially configured this run based on specifications on the BD website and publications using it at the time. I will try to replicate the error and resolve the problem.

Other issues discussing this technology refer to public data on NCBI SRA so it should be possible to use this to test solutions internally before sharing them. Thank you for your help. Please let us know if you manage to solve the problem yourself so we can share it with other users.

Based on current reports, this seems to be an issue specific to the technology settings for BD. Other technologies are not affected. I’ll prioritise updates to be BD settings in the next update but it may take some time. It is helpful to know that several people are interested in using this feature so I hope we can ensure it functions properly.

**Comment by LorenzoLF** [comment] 2023-05-13 14:41
Hi Tom,

Thank you very much for your reply. Indeed, I believe BD modified slightly the barcode specifications in their Enhanced Beads and that is why UniverSC cannot find any matches. I decided to use STARsolo instead [https://github.com/alexdobin/STAR/issues/1607](url) and that worked perfectly.

Thanks and best regards.

**Comment by TomKellyGenetics** [comment] 2023-05-19 01:07
Hi Lorenzo,

Thank you for your thoughtful response. I'm glad you found a suitable alternative in the meantime.

This does explain why there are several unexpected issues related to this specific technology, as noted elsewhere changes have been made by the vendor for this technique.

> In 2022, BD introduced a new version of beads , called Enhanced Beads, which have slightly different oilgo design. The barcodes are the same, but the linker sequences are much shorter than the V1 version
https://teichlab.github.io/scg_lib_structs/methods_html/BD_Rhapsody.html

> Added support for Rhapsody Enhanced bead V2 with an expanded cell label diversity
https://scomix.bd.com/hc/en-us/articles/360047408451-BD-Rhapsody-Analysis-Pipeline-Updates

The regular expressions are not matching due to this difference.

> V1 Indexed-Bead-oligo: |--5'-CCCCCCTCTCTCTCTACACGACGCTCTTCCGATCT[CLS1]ACTGGCCTGCGA[CLS2]GGTAGCGGTGACA[CLS3][8-bp UMI](T)18 -3'
> 
> Enhanced Bead (introduced in 2022): |--5' CCCCCCTCTCTCTCTACACGACGCTCTTCCGATCT[VB][CLS1]GTGA[CLS2]GACA[CLS3][8-bp UMI](T)18 -3'

I added BD settings for V1 specifications more than 2 years ago: https://github.com/search?q=repo%3Aminoda-lab%2Funiversc+rhapsody&type=commits

@kbattenb it seems based on the specifications described by Teichmann lab, it should be possible to support BD V2 beads with minor modifications to the source code. Due to my personal situation it may take a few weeks.

Thanks,

Tom Kelly

**Comment by LorenzoLF** [comment] 2023-05-19 07:46
Hi Tom,

Thank you for the detailed explanation. This clearly pinpoints the issue.

Please let us know once the code is adapted for the Enhanced Beads and thank you very much for the great work on UniverSC!

Best regards.

**Comment by TomKellyGenetics** [comment] 2023-05-25 05:28
@ayyildizd (#10) @Davidwei7 (https://github.com/minoda-lab/universc/issues/13) @paramitadutta14 (https://github.com/minoda-lab/universc/issues/14) @LorenzoLF (#15)
These issues should be resolved in the current development version. SplitSeq (ParseBio) and BD Rhapsody V2 (Becton-Dickinson) will be supported by version 1.2.6, being pushed to GitHub and DockerHub today.

**Closed as completed** 2023-05-25 05:37 UTC
